package main

import (
	"bufio"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"strings"
)

type request struct {
	Version int    `json:"version"`
	Nonce   string `json:"nonce"`
	Proof   string `json:"proof"`
	Input   string `json:"input"`
}
type response struct {
	Version int    `json:"version"`
	Nonce   string `json:"nonce"`
	Code    int    `json:"code"`
	Stdout  string `json:"stdout"`
	Stderr  string `json:"stderr"`
}

// A launch capability is generated by the resident primary for one child only.
// It is not a package key and is never emitted to logs, provenance, or argv.
// The capability proves both peers after the child has reached the gate's
// inherited endpoint; a named-pipe spelling by itself is only routing data.
var gateCapability [32]byte

func newGateCapability() bool { _, err := rand.Read(gateCapability[:]); return err == nil }
func gateProof(label, nonce string) string {
	mac := hmac.New(sha256.New, gateCapability[:])
	_, _ = mac.Write([]byte("service-lasso-primary-v2:" + label + ":" + nonce))
	return base64.StdEncoding.EncodeToString(mac.Sum(nil))
}
func validGateProof(label, nonce, proof string) bool {
	provided, err := base64.StdEncoding.DecodeString(proof)
	if err != nil { return false }
	expected, err := base64.StdEncoding.DecodeString(gateProof(label, nonce))
	return err == nil && hmac.Equal(provided, expected)
}
func gateEnvironment(parent []string, platform, pipe string, fd int) []string {
	result := make([]string, 0, len(parent)+4)
	for _, item := range parent {
		if strings.HasPrefix(item, "SERVICE_LASSO_PRIMARY_GATE=") || strings.HasPrefix(item, "SERVICE_LASSO_PRIMARY_GATE_PIPE=") || strings.HasPrefix(item, "SERVICE_LASSO_PRIMARY_GATE_FD=") || strings.HasPrefix(item, "SERVICE_LASSO_PRIMARY_GATE_CAPABILITY=") { continue }
		result = append(result, item)
	}
	result = append(result, "SERVICE_LASSO_PRIMARY_GATE="+platform, "SERVICE_LASSO_PRIMARY_GATE_CAPABILITY="+base64.StdEncoding.EncodeToString(gateCapability[:]))
	if pipe != "" { result = append(result, "SERVICE_LASSO_PRIMARY_GATE_PIPE="+pipe) }
	if fd > 0 { result = append(result, fmt.Sprintf("SERVICE_LASSO_PRIMARY_GATE_FD=%d", fd)) }
	return result
}

func gateGreeting(connection net.Conn) (string, bool) {
	nonceBytes := make([]byte, 32)
	if _, err := rand.Read(nonceBytes); err != nil { return "", false }
	nonce := hex.EncodeToString(nonceBytes)
	value, err := json.Marshal(struct { Version int `json:"version"`; Nonce string `json:"nonce"`; Proof string `json:"proof"` }{1, nonce, gateProof("gate", nonce)})
	if err != nil { return "", false }
	_, err = connection.Write(append(value, '\n'))
	return nonce, err == nil
}

var heldHelper *os.File
var heldExecutionPath string

func materialize(connection net.Conn) {
	defer connection.Close()
	nonce, ok := gateGreeting(connection)
	if !ok { return }
	line, err := bufio.NewReader(io.LimitReader(connection, 8<<20)).ReadBytes('\n')
	if err != nil {
		return
	}
	var value request
	decoder := json.NewDecoder(bytesReader(line))
	decoder.DisallowUnknownFields()
	if decoder.Decode(&value) != nil || decoder.Decode(&struct{}{}) != io.EOF || value.Version != 1 || value.Nonce != nonce || !validGateProof("sea", nonce, value.Proof) || len(value.Input) == 0 || len(value.Input) > 6<<20 {
		return
	}
	input, err := base64.StdEncoding.DecodeString(value.Input)
	if err != nil {
		return
	}
	if heldExecutionPath == "" { return }
	child := exec.Command(heldExecutionPath)
	if heldHelper != nil { child.ExtraFiles = []*os.File{heldHelper} }
	child.Stdin = bytesReader(input)
	var stdout, stderr limitedBuffer
	child.Stdout, child.Stderr = &stdout, &stderr
	err = child.Run()
	code := 0
	if failure, ok := err.(*exec.ExitError); ok {
		code = failure.ExitCode()
	} else if err != nil {
		return
	}
	encoded, _ := json.Marshal(response{1, nonce, code, base64.StdEncoding.EncodeToString(stdout.Bytes()), base64.StdEncoding.EncodeToString(stderr.Bytes())})
	_, _ = connection.Write(append(encoded, '\n'))
}

type limitedBuffer struct{ value []byte }

func (b *limitedBuffer) Write(value []byte) (int, error) {
	if len(b.value)+len(value) > 1<<20 {
		return 0, fmt.Errorf("protocol output too large")
	}
	b.value = append(b.value, value...)
	return len(value), nil
}
func (b *limitedBuffer) Bytes() []byte { return b.value }

type byteReader struct{ value []byte }

func bytesReader(value []byte) *byteReader { return &byteReader{value} }
func (r *byteReader) Read(target []byte) (int, error) {
	if len(r.value) == 0 {
		return 0, io.EOF
	}
	count := copy(target, r.value)
	r.value = r.value[count:]
	return count, nil
}
