import type { Command, Option } from "commander";

type Shell = "powershell" | "bash" | "zsh";

interface CompletionEntry {
  path: string;
  commands: string[];
  options: string[];
  valueOptions: string[];
}

function optionNames(option: Option): string[] {
  return [option.short, option.long].filter((name): name is string => Boolean(name));
}

function commandName(command: Command): string | undefined {
  const name = command.name();
  return name && name !== "help" ? name : undefined;
}

function completionEntries(program: Command): CompletionEntry[] {
  const rootOptions = program.options.flatMap(optionNames);
  const rootValueOptions = program.options.filter((option) => option.required || option.optional).flatMap(optionNames);
  const entries: CompletionEntry[] = [];

  const visit = (command: Command, path: string[], inheritedOptions: string[], inheritedValueOptions: string[]): void => {
    const childCommands = command.commands.map(commandName).filter((name): name is string => Boolean(name)).sort();
    const ownOptions = command.options.flatMap(optionNames);
    const ownValueOptions = command.options.filter((option) => option.required || option.optional).flatMap(optionNames);
    const options = [...new Set([...inheritedOptions, ...ownOptions])].sort();
    const valueOptions = [...new Set([...inheritedValueOptions, ...ownValueOptions])].sort();
    entries.push({ path: path.join("/"), commands: childCommands, options, valueOptions });
    for (const child of command.commands) {
      const name = commandName(child);
      if (name) visit(child, [...path, name], options, valueOptions);
    }
  };

  visit(program, [], rootOptions, rootValueOptions);
  return entries.sort((left, right) => left.path.localeCompare(right.path));
}

function powershellSource(entries: CompletionEntry[]): string {
  const encoded = Buffer.from(JSON.stringify(entries), "utf8").toString("base64");
  return `# Generated by service-lassoctl; static command and option completion only.\n$script:ServiceLassoCtlCompletion = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${encoded}')) | ConvertFrom-Json\n\nfunction _ServiceLassoCtlComplete {\n  param([string[]]$Words, [string]$WordToComplete)\n  $path = ''\n  $expectValue = $false\n  foreach ($word in $Words | Select-Object -Skip 1) {\n    if ($word -eq '--') { return @() }\n    if ($expectValue) { $expectValue = $false; continue }\n    $entry = $script:ServiceLassoCtlCompletion | Where-Object { $_.path -eq $path } | Select-Object -First 1\n    if ($entry -and $entry.valueOptions -contains $word) { $expectValue = $true; continue }\n    if ($word -notlike '-*' -and $entry -and $entry.commands -contains $word) { $path = if ($path) { \"$path/$word\" } else { $word } }\n  }\n  if ($expectValue) { return @() }\n  $entry = $script:ServiceLassoCtlCompletion | Where-Object { $_.path -eq $path } | Select-Object -First 1\n  if (-not $entry) { return @() }\n  @($entry.commands + $entry.options | Where-Object { $_ -like \"$WordToComplete*\" } | Sort-Object -Unique)\n}\n\nRegister-ArgumentCompleter -Native -CommandName service-lassoctl -ScriptBlock {\n  param($wordToComplete, $commandAst, $cursorPosition)\n  $words = @($commandAst.CommandElements | ForEach-Object { $_.Extent.Text })\n  if ($words.Count -gt 0 -and $words[-1] -eq $wordToComplete) { $words = $words[0..($words.Count - 2)] }\n  _ServiceLassoCtlComplete -Words $words -WordToComplete $wordToComplete | ForEach-Object { [Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_) }\n}\n`;
}

function quotePosix(value: string): string {
  return `'${value.replaceAll("'", "'\\\"'\\\"'")}'`;
}

function posixSource(shell: "bash" | "zsh", entries: CompletionEntry[]): string {
  const rows = entries.map((entry) => `${entry.path}\u001f${entry.commands.join(" ")}\u001f${entry.options.join(" ")}\u001f${entry.valueOptions.join(" ")}`);
  const quotedRows = rows.map(quotePosix).join(" ");
  const setup = shell === "bash"
    ? "complete -F _service_lassoctl_completion service-lassoctl"
    : "if ! (( $+functions[compdef] )); then\n  autoload -Uz compinit\n  compinit -i -D\nfi\ncompdef _service_lassoctl_completion service-lassoctl";
  const wordSource = shell === "bash"
    ? "${COMP_WORDS[@]:1:COMP_CWORD}"
    : "\"${(@)words[2,CURRENT-1]}\"";
  const current = shell === "bash" ? "${COMP_WORDS[COMP_CWORD]}" : "${words[CURRENT]}";
  const reset = shell === "bash" ? "  COMPREPLY=()" : "  reply=()";
  const emit = shell === "bash"
    ? "COMPREPLY=( $(compgen -W \"$candidates\" -- \"$current\") )"
    : "reply=()\n  local candidate\n  for candidate in ${(z)candidates}; do\n    [[ $candidate == \"$current\"* ]] && reply+=(\"$candidate\")\n  done\n  [[ -n ${compstate[context]-} ]] && compadd -- \"${reply[@]}\"";
  return [
    "# Generated by service-lassoctl; static command and option completion only.",
    `_service_lassoctl_rows=(${quotedRows})`,
    "",
    "_service_lassoctl_completion() {",
    "  local path='' word row rowPath commands options valueOptions candidates current expectValue=0",
    reset,
    `  for word in ${wordSource}; do`,
    "    [[ $word == -- ]] && return 0",
    "    if [[ $expectValue -eq 1 ]]; then expectValue=0; continue; fi",
    "    row=''",
    "    for row in \"${_service_lassoctl_rows[@]}\"; do",
    "      IFS=$'\\037' read -r rowPath commands options valueOptions <<< \"$row\"",
    "      [[ $rowPath == $path ]] && break",
    "    done",
    "    [[ \" $valueOptions \" == *\" $word \"* ]] && { expectValue=1; continue; }",
    "    if [[ $word != -* && \" $commands \" == *\" $word \"* ]]; then",
    "      [[ -n $path ]] && path+=/",
    "      path+=\"$word\"",
    "    fi",
    "  done",
    "  [[ $expectValue -eq 1 ]] && return 0",
    "  for row in \"${_service_lassoctl_rows[@]}\"; do",
    "    IFS=$'\\037' read -r rowPath commands options valueOptions <<< \"$row\"",
    "    [[ $rowPath == $path ]] && break",
    "  done",
    `  current=\"${current}\"`,
    "  candidates=\"$commands $options\"",
    `  ${emit}`,
    "}",
    "",
    setup,
    "",
  ].join("\n");
}

export function completionSource(shell: string, program: Command): string {
  const entries = completionEntries(program);
  switch (shell) {
    case "powershell": return powershellSource(entries);
    case "bash": return posixSource("bash", entries);
    case "zsh": return posixSource("zsh", entries);
    default: throw new Error(`Unsupported completion shell: ${shell}`);
  }
}

export const supportedCompletionShells: readonly Shell[] = ["powershell", "bash", "zsh"];
