import { createHash } from "node:crypto";
import { lstat, readdir, readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import { relative, resolve, sep } from "node:path";
import { CliError } from "./errors.js";

export const TEMPLATE_CONTRACT_GATE = Object.freeze({ repository: "service-lasso/service-template", sourceCommit: "bdeb24b84f97e702372ccbcba0794ce30888ad53", templateVersion: "1.0.0-dev", contractDigest: "05162aa2966c3656d5809050398ebaeba354ee6639f51b047464bc6a383324cb", contractSha256: "95e022bf381deb1096f42a0699c4f8f0cfed996670b9d6f0655792d6e41c0f0e", status: "blocked" as const, blocker: "The current service-template develop contract is a development candidate source, not an accepted immutable template artifact.", requiredArtifact: ["immutable tag", "published archive SHA-256", "published template-contract SHA-256", "candidate provenance", "accepted catalog identity"] });
export interface TemplateInventoryEntry { path: string; sha256: string; mode: string; bytes: number; }
export interface TemplateAdmission { repository: string; tag: string; commit: string; templateVersion: string; contractDigest: string; contractSha256: string; archiveSha256: string; catalogIdentity: string; }
export interface AcceptedTemplateBundle extends TemplateAdmission { inventory: TemplateInventoryEntry[]; files: Array<{ path: string; bytes: Buffer; mode: number }>; }
// Source-owned versioned admission data. No caller-controlled path can add an entry.
export const TEMPLATE_ADMISSIONS: readonly TemplateAdmission[] = Object.freeze([]);
const metadata = new Set(["template-contract.json", "template-candidate.json", "template-provenance.json", "service-template.tar.gz"]);
const fail = (message: string): never => { throw new CliError("invalid_template_bundle", message); };
const digest = (bytes: Buffer): string => createHash("sha256").update(bytes).digest("hex");
const sha = (value: unknown, length: number): value is string => typeof value === "string" && new RegExp(`^[a-f0-9]{${length}}$`).test(value);
function safe(path: string): string { if (path.includes("\\") || path.startsWith("/") || path.split("/").some((part) => !part || part === "." || part === "..")) fail("Template inventory contains an unsafe path."); return path; }
function closed(value: unknown, keys: readonly string[], message: string): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value) || Object.keys(value).length !== keys.length || Object.keys(value).some((key) => !keys.includes(key))) fail(message); return value as Record<string, unknown>; }
// JSON.parse overwrites duplicate object members; reject duplicates before it can do so.
function json(bytes: Buffer, message: string): unknown { const text = bytes.toString("utf8"); let i = 0; const ws = () => { while (/\s/.test(text[i] ?? "")) i++; }; const str = (): string => { const start = i++; let escaped = false; while (i < text.length) { const c = text[i++]; if (escaped) { escaped = false; continue; } if (c === "\\") { escaped = true; continue; } if (c === '"') return JSON.parse(text.slice(start, i)); } return fail(message); }; const val = (): void => { ws(); if (text[i] === '"') { str(); return; } if (text[i] === "{") { obj(); return; } if (text[i] === "[") { arr(); return; } const m = /^(?:true|false|null|-?(?:0|[1-9]\d*)(?:\.\d+)?(?:[eE][+-]?\d+)?)/.exec(text.slice(i)); if (!m) fail(message); i += m![0].length; }; const obj = (): void => { i++; ws(); const seen = new Set<string>(); if (text[i] === "}") { i++; return; } for (;;) { ws(); if (text[i] !== '"') fail(message); const key = str(); if (seen.has(key)) fail(message); seen.add(key); ws(); if (text[i++] !== ":") fail(message); val(); ws(); if (text[i] === "}") { i++; return; } if (text[i++] !== ",") fail(message); } }; const arr = (): void => { i++; ws(); if (text[i] === "]") { i++; return; } for (;;) { val(); ws(); if (text[i] === "]") { i++; return; } if (text[i++] !== ",") fail(message); } }; val(); ws(); if (i !== text.length) fail(message); try { return JSON.parse(text); } catch { return fail(message); } }
function text(bytes: Buffer): string { const end = bytes.indexOf(0); return bytes.subarray(0, end < 0 ? bytes.length : end).toString("utf8"); }
function octal(bytes: Buffer): number { const value = text(bytes).trim(); if (!/^[0-7]+$/.test(value)) fail("Template archive contains an invalid header."); const result = Number.parseInt(value, 8); if (!Number.isSafeInteger(result)) fail("Template archive contains an invalid header."); return result; }
function archive(bytes: Buffer): Map<string, { bytes: Buffer; mode: string }> { if (bytes.length > 16 * 1024 * 1024) fail("Template archive exceeds the accepted size."); let tar = Buffer.alloc(0); try { tar = gunzipSync(bytes, { maxOutputLength: 64 * 1024 * 1024 }); } catch { fail("Template archive is invalid or exceeds the accepted size."); } const result = new Map<string, { bytes: Buffer; mode: string }>(); let offset = 0; while (offset < tar.length) { const header = tar.subarray(offset, offset + 512); if (header.length !== 512) fail("Template archive is truncated."); if (header.every((value) => value === 0)) { if (!tar.subarray(offset).every((value) => value === 0)) fail("Template archive has trailing data."); break; } const name = safe(text(header.subarray(345, 500)) ? `${text(header.subarray(345, 500))}/${text(header.subarray(0, 100))}` : text(header.subarray(0, 100))); const mode = octal(header.subarray(100, 108)).toString(8).padStart(4, "0"), size = octal(header.subarray(124, 136)), type = header[156]; if (![0, 48].includes(type) || !/^(0644|0755)$/.test(mode) || result.has(name)) fail("Template archive contains an unsafe entry."); const start = offset + 512, end = start + size; if (end > tar.length) fail("Template archive is truncated."); result.set(name, { bytes: Buffer.from(tar.subarray(start, end)), mode }); offset = start + Math.ceil(size / 512) * 512; } if (!result.size) fail("Template archive contains no files."); return result; }
async function rootFiles(root: string): Promise<Set<string>> { const result = new Set<string>(); const walk = async (directory: string, prefix = ""): Promise<void> => { for (const entry of await readdir(directory, { withFileTypes: true }).catch(() => fail("Template bundle is incomplete."))) { const path = prefix ? `${prefix}/${entry.name}` : entry.name, stat = await lstat(resolve(directory, entry.name)).catch(() => fail("Template payload is unavailable.")); if (stat.isSymbolicLink() || (!stat.isFile() && !stat.isDirectory())) fail("Template payload contains a reparse or unsafe entry."); if (stat.isDirectory()) await walk(resolve(directory, entry.name), path); else result.add(path); } }; await walk(root); return result; }
export function templateContractPreview(): Record<string, unknown> { return TEMPLATE_CONTRACT_GATE; }
export function requireAcceptedTemplateIdentity(): never { throw new CliError("template_identity_unavailable", "No accepted immutable service-template identity is available; project creation is blocked until the template owner publishes and accepts the checksum-bound candidate."); }
export async function loadAcceptedTemplateBundle(templateRoot: string, admissions: readonly TemplateAdmission[] = TEMPLATE_ADMISSIONS): Promise<AcceptedTemplateBundle> { const root = resolve(templateRoot); const [contractBytes, candidateBytes, provenanceBytes, archiveBytes] = await Promise.all([readFile(resolve(root, "template-contract.json")), readFile(resolve(root, "template-candidate.json")), readFile(resolve(root, "template-provenance.json")), readFile(resolve(root, "service-template.tar.gz"))]).catch(() => fail("Accepted template bundle is incomplete.")); const message = "Accepted template bundle metadata is invalid.", contract = closed(json(contractBytes, message), ["schemaVersion", "contractDigest", "inventory"], message), candidate = closed(json(candidateBytes, message), ["schemaVersion", "templateCommit", "templateVersion", "contractDigest", "contractSha256", "archiveSha256", "releaseTag"], message), provenance = closed(json(provenanceBytes, message), ["schemaVersion", "templateRepository", "templateCommit", "templateVersion", "contractDigest", "catalogIdentity", "origin"], message);
  if (contract.schemaVersion !== 1 || !sha(contract.contractDigest, 64) || !Array.isArray(contract.inventory) || candidate.schemaVersion !== 1 || provenance.schemaVersion !== 1) fail(message); if (!sha(candidate.templateCommit, 40) || !sha(candidate.archiveSha256, 64) || !sha(candidate.contractSha256, 64) || !sha(candidate.contractDigest, 64) || candidate.contractSha256 !== digest(contractBytes) || candidate.archiveSha256 !== digest(archiveBytes) || candidate.contractDigest !== contract.contractDigest) fail("Accepted template bundle checksum metadata is invalid."); if (typeof candidate.templateVersion !== "string" || typeof candidate.releaseTag !== "string" || candidate.releaseTag !== `template-v${candidate.templateVersion}-${candidate.templateCommit}` || !/^template-v[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?-[a-f0-9]{40}$/.test(candidate.releaseTag) || candidate.templateVersion.includes("dev")) fail("Template bundle is not an accepted immutable release."); const origin = closed(provenance.origin, ["kind"], "Accepted template provenance is incomplete."); if (provenance.templateRepository !== "service-lasso/service-template" || provenance.templateCommit !== candidate.templateCommit || provenance.templateVersion !== candidate.templateVersion || provenance.contractDigest !== candidate.contractDigest || typeof origin.kind !== "string" || !origin.kind || typeof provenance.catalogIdentity !== "string" || !provenance.catalogIdentity) fail("Accepted template provenance is incomplete.");
  const admission = admissions.find((item) => item.repository === provenance.templateRepository && item.tag === candidate.releaseTag && item.commit === candidate.templateCommit && item.templateVersion === candidate.templateVersion && item.contractDigest === candidate.contractDigest && item.contractSha256 === candidate.contractSha256 && item.archiveSha256 === candidate.archiveSha256 && item.catalogIdentity === provenance.catalogIdentity); if (!admission) requireAcceptedTemplateIdentity();
  const inventory: TemplateInventoryEntry[] = (contract.inventory as unknown[]).map((entry: unknown) => { const item = closed(entry, ["path", "sha256", "mode", "bytes"], "Template inventory is invalid."); if (typeof item.path !== "string" || !sha(item.sha256, 64) || !/^(0644|0755)$/.test(item.mode as string) || !Number.isSafeInteger(item.bytes) || (item.bytes as number) < 0) fail("Template inventory is invalid."); return { path: safe(item.path as string), sha256: item.sha256 as string, mode: item.mode as string, bytes: item.bytes as number }; }); if (!inventory.length || new Set(inventory.map((item) => item.path)).size !== inventory.length) fail("Template inventory is invalid."); const archived = archive(archiveBytes), expected = new Set(inventory.map((item) => item.path)), found = await rootFiles(root); for (const path of found) if (!metadata.has(path) && !expected.has(path)) fail("Template payload contains an unknown entry."); for (const name of metadata) if (!found.has(name)) fail("Accepted template bundle is incomplete."); const files = inventory.map((item) => { const value = archived.get(item.path); if (!value) fail("Template archive does not match its inventory."); const held = value!; if (held.mode !== item.mode || held.bytes.length !== item.bytes || digest(held.bytes) !== item.sha256) fail("Template archive does not match its inventory."); return { path: item.path, bytes: held.bytes, mode: Number.parseInt(item.mode, 8) }; }); if (archived.size !== inventory.length || [...archived.keys()].some((path) => !expected.has(path))) fail("Template archive does not match its inventory."); for (const item of inventory) { const path = resolve(root, item.path); if (!path.startsWith(root + sep) || relative(root, path).startsWith("..")) fail("Template inventory contains an unsafe path."); const stat = await lstat(path).catch(() => fail("Template payload does not match its inventory.")); if (!stat.isFile() || stat.isSymbolicLink() || (process.platform !== "win32" && (stat.mode & 0o777) !== Number.parseInt(item.mode, 8))) fail("Template payload contains an unsafe file."); if (!(await readFile(path)).equals(files.find((file) => file.path === item.path)!.bytes)) fail("Template payload does not match its archive."); }
  return { ...admission, inventory, files }; }
export async function acceptedTemplateFiles(bundle: AcceptedTemplateBundle): Promise<Array<{ path: string; bytes: Buffer; mode: number }>> { return bundle.files.map((file) => ({ ...file, bytes: Buffer.from(file.bytes) })); }
